### ISSUE TITLE
Oxygen Not Included 中文包

### ISSUE THREAD

**Issue by z17898** [DolphinWing/DSTTranslate#12]
建立新遊戲內的遊戲設定顯示英文 Worldgen Seed, Disease, Hunger... 等等
模組內核取方塊左邊的"選項"顯示簡體

請問怎麼改善這個問題
我在strings和內建的strings_preinstalled檔案內都找不到這些字串

**Comment by DolphinWing** [comment]
找不到的字串通常是MOD自己帶的文字，有些MOD會提供多國翻譯檔，有些則是寫死在程式碼內。
我之前有試著到MOD的資料夾裡面去看他們定義的字串，然後在模組裡面加。
不過不是每個MOD的每個字串都能套的上。
最容易的方式是詢問原MOD作者，如果要幫他們翻譯行不行。

我之前有發現，裝了生成世界相關的一些MOD可能會導致在建立遊戲的選單沒有套用到我想要翻譯的字串。
不確定是不是因為MOD改變了一些行為導致。

**Comment by z17898** [comment]
了解 感謝解答!
